version: "3"

networks:
 kong-net:
  driver: bridge

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-db:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 5s
      timeout: 3s
      retries: 5
    stdin_open: true
    tty: true
    volumes:
      - ./kong-pgdata:/var/lib/postgresql/data

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
    networks:
      - kong-net


  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    depends_on:
      - kong-db
      - kong-migration
    restart: always
    networks:
      - kong-net
    environment:
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_ADMIN_LISTEN: 'kong:8001'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "80:8000"

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: "${KONGA_DOCKER_TAG:-pantsel/konga:latest}"
    command: "-c prepare -a postgres -u postgresql://${KONG_PG_USER:-kong}:${KONG_PG_PASSWORD:-kong}@kong-db:5432/konga_db"
    restart: on-failure
    networks:
      - kong-net
    depends_on:
      - kong-db

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: "${KONGA_DOCKER_TAG:-pantsel/konga:latest}"
    restart: always
    networks:
      - kong-net
    environment:
      TOKEN_SECRET: ${KONGA_SECRET:-somerandomsecret}
      DB_ADAPTER: postgres
      DB_HOST: kong-db
      DB_USER: ${KONG_PG_USER:-kong}
      DB_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      DB_DATABASE: ${KONG_PG_DATABASE:-kong}
      NODE_ENV: ${KONGA_NODE_ENV:-development}
    depends_on:
      - kong-db
    ports:
      - "1337:1337"
